export  const  SINGLE_PRODUCT_GET_REQUEST="SINGLE_PRODUCT_GET_REQUEST"
export  const  SINGLE_PRODUCT_GET_SUCESS="SINGLE_PRODUCT_GET_SUCESS"
export  const  SINGLE_PRODUCT_GET_ERROR="SINGLE_PRODUCT_GET_ERROR"
